Add runs endpoint
eclipse-apoapsis/ort-server pull request #1139
Opened 2024-10-02 12:51 UTC by lamppu

Please see individual commits for details.

Resolves https://github.com/eclipse-apoapsis/ort-server/issues/1074.

2024-10-03 14:13 UTC, Etsija commented
If this resolves #1074, it should be mentioned in the description.

2024-10-03 14:16 UTC, sschuberth commented
Please rebase to resolve a merge conflict.

2024-10-03 16:52 UTC, sschuberth commented
> If this resolves #1074, it should be mentioned in the description.

Actually not in the PR description, but in the commit message.

2024-10-04 05:17 UTC, Etsija commented
> > If this resolves #1074, it should be mentioned in the description.
> 
> Actually not in the PR description, but in the commit message.

Really? This PR consists of five commits, which together resolve the issue. In these cases, I've always put the "Resolves..." text to the PR description, because no individual commit of those five is responsible for resolving the issue. Can you elaborate why we would tag only one commit (and which? The latest one?) for resolving the issue?

2024-10-04 06:37 UTC, sschuberth commented
> Really?

Yes, really. 

> Can you elaborate why we would tag only one commit, and which one should it be?

Assume that all but the last commit were already there, maybe created by someone else. Then logically it would still be the last commit that concludes the resolution of the issue.

Also, it does not make sense to sometimes resolve issues in commits and other times in PRs. To have one easy to remember rule, we align on the former. 

> I understand that PR descriptions are not seen in the commit history, so it would make sense to refer to issues being resolved in commit messages, but when looking at commit history, I see varying approaches to this, so maybe it should be discussed with the team.

This is not a team decision, but a project lead decision, IMO. So @mnonnenmacher has the last say. I tried to point it out in all PRs that I reviewed if the resolution was done in the PR instead of the commit. Could be that I missed some occurrences. But if it was not done in the commit, it's a mistake, IMO.

2024-10-04 10:26 UTC, mnonnenmacher commented
> > Really?
> 
> Yes, really.
> 
> > Can you elaborate why we would tag only one commit, and which one should it be?
> 
> Assume that all but the last commit were already there, maybe created by someone else. Then logically it would still be the last commit that concludes the resolution of the issue.
> 
> Also, it does not make sense to sometimes resolve issues in commits and other times in PRs. To have one easy to remember rule, we align on the former.

In my experience it's sufficient to only link the commit that does the final change to fix an issue, like the last one in this PR, this provides enough context already and it's easy to find the PR from there. However, you could also link the previous commits by using "Relates to #12345" if you think that is important, I sometimes do this when I only partly fix an issue. To me adding the link to the PR description is optional but adding it to the commit is mandatory.

> > I understand that PR descriptions are not seen in the commit history, so it would make sense to refer to issues being resolved in commit messages, but when looking at commit history, I see varying approaches to this, so maybe it should be discussed with the team.
> 
> This is not a team decision, but a project lead decision, IMO. So @mnonnenmacher has the last say. I tried to point it out in all PRs that I reviewed if the resolution was done in the PR instead of the commit. Could be that I missed some occurrences. But if it was not done in the commit, it's a mistake, IMO.

The definition of the role is mainly about organizational responsibilities, but a project lead is not automatically a technical lead:
https://www.eclipse.org/projects/handbook/#roles-pl
It specifically says:

> A project lead is not necessary a technical lead. We have no formal designation of technical lead; this tends to occur organically.

This matches with my experience that the people who are most active in contributing and reviewing code automatically have more influence on technical decisions.

2024-10-04 16:01 UTC, mnonnenmacher requested changes

2024-10-04 16:01 UTC, mnonnenmacher commented on api/v1/model/src/commonMain/kotlin/FilterOperatorAndValue.kt
> +enum class SqlOperator {
I think I would prefer a more generic name like `ComparisonOperator`, at least in the API module. Mentioning SQL here exposes an implementation detail and they might in future also be used for requests that do get their data from the database, like the user endpoints.

2024-10-04 16:18 UTC, sschuberth commented
I believe you might need to rebase once more to make the new prettier checks work property.

2024-10-07 16:16 UTC, mnonnenmacher approved these changes
Very nice PR!
@lamppu  You need to rebase once more because there are conflicts.

2024-10-08 06:14 UTC, sschuberth approved these changes

2024-10-08 06:50 UTC, merged