ci: Downgrade Tanstack Router to 1.31.20
eclipse-apoapsis/ort-server pull request #209
Opened 2024-05-08 14:03 UTC by Etsija

Tanstack Router 1.31.23 has a breaking bug [1] which prevents UI to work. Downgrading to 1.31.20 fixes the issue.

[1] https://github.com/TanStack/router/issues/1570https://github.com/TanStack/router/issues/1570

2024-05-08 14:04 UTC, mnonnenmacher reviewed
There's a `:` missing after `[1]` in the commit message.

2024-05-08 14:22 UTC, mmurto requested changes
The lockfile should also be updated by running `pnpm install`.

2024-05-08 14:24 UTC, sschuberth commented
> The lockfile should also be updated by running `pnpm install`.

FYI, that command also has a `--lockfile-only` option, like `pnpm -C ui install --lockfile-only`.

2024-05-08 14:36 UTC, mnonnenmacher commented
> > The lockfile should also be updated by running `pnpm install`.
> 
> FYI, that command also has a `--lockfile-only` option, like `pnpm -C ui install --lockfile-only`.

While playing around with ESLint I had the impression that `pnpm install` also modified unrelated lockfile entries while `pnpm add -D lib@version` edited only the relevant parts of the lockfile. Just in case it helps, could also be that I'm wrong.

2024-05-08 14:56 UTC, sschuberth commented
> I had the impression that `pnpm install` also modified unrelated lockfile entries

I guess that's because it really (re-)installs *everything*, not just the one modified entry from `package.json`, and depending on when you ran `install` last, a lot of other dependencies might have changed as well.

2024-05-08 16:46 UTC, Etsija commented
I will fix the PR tomorrow.

2024-05-08 17:55 UTC, mmurto commented
I was wondering why the build in CI was passing even though the `package.json` and `pnpm-lock.yaml` were not in sync, [which shouldn't happen on CI](https://pnpm.io/cli/install#--frozen-lockfile), leading to #210 . Outdated lockfile should error after that is merged.

2024-05-09 12:45 UTC, mmurto commented
This was fixed in Router, so #212 should be merged instead of this.

2024-05-09 12:51 UTC, closed without merging

2024-05-09 12:52 UTC, Etsija commented
Closed as another PR fixes this.