ui: Add Scanner and Evaluator jobs
eclipse-apoapsis/ort-server pull request #267
Opened 2024-05-21 10:09 UTC by Etsija

This PR adds more job configurations to an ORT Run: Scanner and Evaluator can now be configured and run as part of an ORT run.  Moreover, enabling and disabling jobs from a run is implemented.

NOTE: Issue #236 makes all ORT runs fail if Reporter job is enabled.  It has been verified that with only Analyzer and Scanner (but not Reporter) jobs enabled, the Analyzer runs successfully, after which the Scanner is started and it also runs successfully.

2024-05-21 12:14 UTC, mmurto requested changes

2024-05-21 12:14 UTC, mmurto commented on ui/src/routes/_layout/organizations/$orgId.products.$productId.repositories.$repoId.create-run.tsx
> + * distributed under the License is distributed on an 'AS IS' BASIS,
These are probably left over from some search and replace? At least for me Prettier doesn't format these, so these should be changed back to ".

2024-05-21 12:14 UTC, mmurto commented on ui/src/routes/_layout/organizations/$orgId.products.$productId.repositories.$repoId.create-run.tsx
> +          enabledPackageManagers:
It could be useful to add a code commet here for why this is done.

2024-05-22 07:05 UTC, mmurto approved these changes

2024-05-22 08:31 UTC, Etsija commented on ui/package.json
> +    "@radix-ui/react-accordion": "^1.1.2",
It _was_ a separate commit - until I ran into rebase turmoil due to numerous changes today to UI deps, and something broke.

2024-05-22 08:33 UTC, Etsija commented on ui/src/routes/_layout/organizations/$orgId.products.$productId.repositories.$repoId.create-run.tsx
> +] as const;
There's also the `reportFormats` list in this component, which is unnecessary repetition.

2024-05-22 10:21 UTC, sschuberth commented on ui/package.json
> +    "@radix-ui/react-accordion": "^1.1.2",
This should now be separate again. Please have a look both.

2024-05-22 10:31 UTC, Etsija commented on ui/package.json
> +    "@radix-ui/react-accordion": "^1.1.2",
Fine by me.

2024-05-22 14:32 UTC, mnonnenmacher approved these changes

2024-05-22 14:50 UTC, merged