feat(ui): Show version information on about page
eclipse-apoapsis/ort-server pull request #617
Opened 2024-07-05 11:13 UTC by lamppu

![Näyttökuva (91)](https://github.com/eclipse-apoapsis/ort-server/assets/26835550/9d65f7f0-8635-4fd6-8c18-b1b296822585)

2024-07-05 11:20 UTC, sschuberth commented
> Resolves #608

Please put this (with a trailing dot) into the commit message, not in the PR discussion.

2024-07-05 11:21 UTC, sschuberth commented on ui/src/routes/_layout/about/index.tsx
> +            <h3 className='font-semibold'>Server and tool versions:</h3>
As the data can contain arbitrary names and versions, I'd more generally just say "Version information:".

2024-07-05 12:08 UTC, mmurto requested changes

2024-07-05 12:08 UTC, mmurto commented on ui/src/routes/_layout/about/index.tsx
> +    <>
No need for `<>` as there's only one direct child.

2024-07-05 12:53 UTC, mmurto approved these changes

2024-07-05 13:08 UTC, merged

2024-07-08 11:34 UTC, sschuberth commented
@lamppu stupid question maybe, but how do I actually access the about screen? I don't see it anywhere...

2024-07-08 11:55 UTC, lamppu commented
> @lamppu stupid question maybe, but how do I actually access the about screen? I would have expected it to be accessible from the profile icon, but it's not there for me:
> 
> ![image](https://private-user-images.githubusercontent.com/349154/346544356-44c3fdd7-312b-427f-910d-1436257ff30c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0Mzk5MDYsIm5iZiI6MTcyMDQzOTYwNiwicGF0aCI6Ii8zNDkxNTQvMzQ2NTQ0MzU2LTQ0YzNmZGQ3LTMxMmItNDI3Zi05MTBkLTE0MzYyNTdmZjMwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOFQxMTUzMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNTkxZWEyMjUyNmE2MjIyN2MwYWFkMWIyOTFhNDFjMGNlNDk5ZmJhOWZmMjNlMjJjMTQyZjA5YzFjZWY3MGRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WP2nxM9KxnF7ukirNJ0JhTAhzXoiRkk8nOlxhpuMzP0)

Oh yeah sorry, I forgot to add the link. You can browse to /about for now (e.g. http://localhost:5173/about)

2024-07-08 19:55 UTC, sschuberth commented
> Oh yeah sorry, I forgot to add the link.

I gave it a try to add it at https://github.com/eclipse-apoapsis/ort-server/pull/639.