feat(dev): Add basic environment and requests for IDEA HTTP client
eclipse-apoapsis/ort-server pull request #9
Opened 2024-04-04 10:09 UTC by MarcelBochtler

Add requests to read and create the basic ORT server entities with the IDEA HTTP client [1].
This setup expects a `http-client.private.env.json` file that configures the authentication.

[1]: https://www.jetbrains.com/help/idea/http-client-in-product-code-editor.html

2024-04-05 08:24 UTC, MarcelBochtler commented
Discussion:
I added only a very basic number of requests to keep it simple.
We could also import all the requests from our OpenApi spec. But I'm not sure if this would add too many and will make it more complex.

2024-04-05 10:22 UTC, mnonnenmacher requested changes
Could you add a README to the `requests` dir that briefly explains what these files are about and than IntelliJ Ultimate license is required to use them?

2024-04-05 10:22 UTC, mnonnenmacher commented on .gitignore
> +# Private http requests
Nit: HTTP (as in comment above)

2024-04-05 10:33 UTC, mnonnenmacher commented
> Discussion: I added only a very basic number of requests to keep it simple. We could also import all the requests from our OpenApi spec. But I'm not sure if this would add too many and will make it more complex.

I think it's good to start with a small number of requests to keep it maintainable.

2024-04-08 11:48 UTC, mnonnenmacher approved these changes

2024-04-08 12:05 UTC, merged