Introduce enums for the severity
eclipse-apoapsis/ort-server pull request #923
Opened 2024-08-28 15:40 UTC by mnonnenmacher

Please see the commit messages for details.

2024-08-28 15:44 UTC, sschuberth requested changes

2024-08-28 15:44 UTC, sschuberth commented on api/v1/model/src/commonMain/kotlin/Severity.kt
> +    ERROR;
Nit: The semicolon can be omitted if no functions follow.

2024-08-28 15:44 UTC, sschuberth commented on model/src/commonMain/kotlin/Severity.kt
> +    ERROR;
Nit: The semicolon can be omitted if no functions follow.

2024-08-28 15:44 UTC, sschuberth commented on api/v1/model/src/commonMain/kotlin/Severity.kt
> +    ERROR
Wrong commit 😉

2024-08-28 15:44 UTC, sschuberth commented on model/src/commonMain/kotlin/Severity.kt
> +    ERROR
Wrong commit 😉

2024-08-29 07:58 UTC, nnobelis commented on workers/reporter/src/test/kotlin/reporter/ReporterRunnerTest.kt
Does this change belong to this commit ?

2024-08-29 08:09 UTC, mnonnenmacher commented on workers/reporter/src/test/kotlin/reporter/ReporterRunnerTest.kt
Moved it to the previous commit.

2024-08-29 08:49 UTC, nnobelis approved these changes

2024-08-29 12:42 UTC, merged